function [savename] = BLSaving(velocity_mean,velocity_mean_r,...
    velocity_mean_s,velocity_rms,velocity_rms_r,...
    velocity_rms_s,mean_SNR,mean_R2,mean_signal,...
    pixel_um_resolution,emissionlocatingdata,...
    run,invar_image_compare,loc_data,row_mm,row_mm_uncertainty,...
    uncertainty_wall_loc_pix,tau_fit,...
    doublegauss_fitvariables,constant_background,...
    gate1_location_bounds,gate2_location_bounds,...
    synthfilepath,synth_switch,nondim_velo_error,...
    synth_input_tau_fit,synth_input_velocity_mean,...
    zero_height_ref_unc,sufficient_counter,background_totalfit,...
    filt_centroids)
%Saves the data for later visualization or synthetic correction

%% Trim data down to be nice and continuous and only report relevent geometric ranges
    %trim the data to be 0-12mm
    list_continuous = (row_mm>=0)&(row_mm<=row_mm(min(sufficient_counter)));

    %trim data using the continuous list of data
    velocity_mean   = velocity_mean(list_continuous);
    velocity_mean_r = velocity_mean_r(list_continuous);
    velocity_mean_s = velocity_mean_s(list_continuous);
    velocity_rms    = velocity_rms(list_continuous);
    velocity_rms_r  = velocity_rms_r(list_continuous);
    velocity_rms_s  = velocity_rms_s(list_continuous);
    mean_SNR        = mean_SNR(list_continuous);
    mean_R2         = mean_R2(list_continuous);
    mean_signal     = mean_signal(list_continuous);
    row_mm          = row_mm(list_continuous);
    row_mm_uncertainty = row_mm_uncertainty(list_continuous);
    tau_fit         = tau_fit(list_continuous);
    doublegauss_fitvariables = doublegauss_fitvariables(list_continuous,:);
    gate1_location_bounds = gate1_location_bounds(list_continuous,:);
    gate2_location_bounds = gate2_location_bounds(list_continuous,:);


%% Save Data
num_images = invar_image_compare;
rows = length(velocity_rms);
velocimetry_geometricloc = zeros(rows,6);
velocimetry_geometricloc(:,1:2) = repmat(loc_data(1,:),rows,1); %x
velocimetry_geometricloc(:,3:4) = repmat(loc_data(2,:),rows,1); %y
velocimetry_geometricloc(:,5) = row_mm;
velocimetry_geometricloc(:,6) = row_mm_uncertainty;

    if synth_switch
    savename = ['ProcessedData/ProcessedData_Synth_Run',num2str(run),'_Images',num2str(num_images),'.mat'];
    save(savename,'velocity_mean','velocity_mean_r',...
        'velocity_mean_s','velocity_rms','velocity_rms_r',...
        'velocity_rms_s','mean_SNR','mean_R2','mean_signal',...
        'pixel_um_resolution','emissionlocatingdata',...
        'run','invar_image_compare','velocimetry_geometricloc',...
        'tau_fit','doublegauss_fitvariables',...
        'constant_background','gate1_location_bounds','gate2_location_bounds',...
        'list_continuous','nondim_velo_error','synth_input_tau_fit','synth_input_velocity_mean');

    else %real data
    savename = ['ProcessedData/ProcessedData_Run',num2str(run),'_Images',num2str(num_images),'.mat'];
    save(savename,'velocity_mean','velocity_mean_r',...
        'velocity_mean_s','velocity_rms','velocity_rms_r',...
        'velocity_rms_s','mean_SNR','mean_R2','mean_signal',...
        'pixel_um_resolution','emissionlocatingdata',...
        'run','invar_image_compare','velocimetry_geometricloc',...
        'tau_fit','doublegauss_fitvariables',...
        'constant_background','gate1_location_bounds','gate2_location_bounds',...
        'list_continuous','zero_height_ref_unc','background_totalfit');
    end

    if ~synth_switch
    savename = ['Fit_images/R',num2str(run),'/filtcents_ims',num2str(num_images),'.mat'];
    save(savename,'filt_centroids');
    end

end